language: python

python: 
  - 3.5

# script:
#   - python manage.py 

before_script:
- python manage.py syncdb --noinput
- python manage.py runserver 0.0.0.0:8000 &
env:
  - DJANGO=2.0.12

deploy:
  keyfile: client-secret.json
  provider: gae
  project: forumbackend
  default: true
  docker-build: remote
  on:
    branches:    # ← new!
      only:      # ← new!
        - master # ← new!
  run:
    python manage.py syncdb --noinput
true:
  branch: master
services: postgresql

before_install:
- openssl aes-256-cbc -K $encrypted_f4d948b86ff3_key -iv $encrypted_f4d948b86ff3_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
- tar xvzf credentials.tar.gz 
- export DJANGO_SETTINGS_MODULE=rengorum.settings
- export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt

email: false